# Generated by Django 3.0.6 on 2020-06-06 10:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200606_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=20, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='club',
            name='created_as',
            field=models.TimeField(default=datetime.datetime(2020, 6, 6, 10, 36, 56, 753095, tzinfo=utc), verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 10, 36, 56, 711097, tzinfo=utc), verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 10, 36, 56, 753095, tzinfo=utc), verbose_name='日付'),
        ),
    ]
